### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by JDragan** [enthus1ast/nimWebTemplates#2]
Nice project, it has lot of potential.

I saw [tfor.nwt](https://github.com/enthus1ast/nimWebTemplates/blob/master/future/tfor.nwt)
Are there any plans to implement them and when?

Also, can you serve CSS styles without using Jester?

**Comment by enthus1ast** [comment]
the initial plan was to be able to copy over my old jinja templates 
so `for` `if` and friends are planned and i've also had a half working branch based on nim macros, the issue with macros was that they require recompilation. Unfortunately i cannot give you any estimation when this is finished. 
But i've recently used "https://github.com/onionhammer/nim-templates" which can loop but also requires recompilation.

for css:
In principal you can generate any text output with nwt, 
When you want to serve the generated text as a http/css page you need a webserver. 
For simple things `asynchttpserver` is fine. 

The only thing you should do is set the content-type header aproperately.
so for example when you want to serve css:


```nim
import asynchttpserver, asyncdispatch, uri, nwt


proc cb(req: Request, tmpl: Nwt) {.async.} =
    echo req.url
    case req.url.path
    of "/styles.css":
        let headers = newHttpHeaders({ "Content-Type": "text/css" })
        await req.respond(Http200, tmpl.renderTemplate("styles.css"), headers)
    of "/":
        let headers = newHttpHeaders({ "Content-Type": "text/html" })
        await req.respond(Http200, tmpl.renderTemplate("index.html"), headers)
    else:
        await req.respond(Http404, "not found")
    
when isMainModule:
    var tmpl = newNwt()
    tmpl.addTemplate("index.html", 
    """
    <html>
    <head>
        <link href="/styles.css" rel="stylesheet">
    </head>
    <body>
        <h1>Hi! :)</h1>
    <body>
    </html>
    """)
    tmpl.addTemplate("styles.css", "body {background-color: blue;}" )
    var server = newAsyncHttpServer()
    waitFor server.serve(Port(8080), proc (req: Request): Future[void] {.gcsafe.} = cb(req, tmpl))
```

**Comment by enthus1ast** [comment]
working on a new implementation in nwt2 branch

**Comment by enthus1ast** [comment]
the new implementation lives here: [nimja](https://github.com/enthus1ast/nimja). nimWebTemplates is deprecated
