### ISSUE TITLE
No issue. Thanks and a comment.

### ISSUE THREAD

**Issue by UNIcodeX** [enthus1ast/nimWebTemplates#3]
First: Thank you for starting this project. Jinja is my go-to web page templating framework when using Python's Flask, Quart, Sanic, etc... Your implementation is already saving me a ton of time porting Python web app(s) to Nim's Jester and Prologue.

Second: Possibly missed naming opportunities:
```
1) Nimja
2) Ninja
```

There's this Nim project named Nimja, but I'm not sure what it does :sweat_smile: and it seems to be abandoned. Looks like maybe a ??Java build system??
https://github.com/RedBeard0531/nimja

Anyway. The only issue I had was when trying to install it with nimble. I was looking for `nimWebTemplates` and several permutations, but it's actually `nwt`. Once one knows that, it's no big deal, but it wasn't immediately obvious to me.

Keep being awesome.

**Comment by keshon** [comment]
Ninja sounds awesome and fits perfectly to Ninja Web template (NWT). Adds quite a personality to the project :) Cheers!

**Comment by enthus1ast** [comment]
@UNIcodeX the new implementation lives here: [nimja](https://github.com/enthus1ast/nimja). 
Nimja should be capable of porting most of jinja code.
@keshon nimja it is ;)
